CREATE DATABASE UniDloX
GO
USE UniDloX
GO


CREATE TABLE MsCustomer(
	CustomerId VARCHAR(5) PRIMARY KEY CHECK(CustomerId LIKE 'CU[0-9][0-9][0-9]') NOT NULL,
	CustomerName CHAR(50) NOT NULL,
	CustomerPhoneNumber VARCHAR(15) NOT NULL,
	CustomerAddress VARCHAR(100) NOT NULL,
	CustomerGender CHAR(10) CHECK(CustomerGender LIKE 'Male' OR CustomerGender LIKE 'Female') NOT NULL,
	CustomerEmail VARCHAR(100) CHECK (CustomerEmail LIKE '%@gmail.com' OR CustomerEmail LIKE '%@yahoo.com') NOT NULL,
	CustomerDOB DATE NOT NULL
)

CREATE TABLE MsStaff(
	StaffId VARCHAR(5) PRIMARY KEY CHECK(StaffId LIKE 'SF[0-9][0-9][0-9]') NOT NULL,
	StaffName CHAR(50) NOT NULL,
	StaffPhoneNumber VARCHAR(15) NOT NULL,
	StaffAddress VARCHAR(100) CHECK(LEN (StaffAddress) > 10 AND LEN (StaffAddress) < 15) NOT NULL,
	StaffAge INT NOT NULL,
	StaffGender CHAR(10) CHECK(StaffGender LIKE 'Male' OR StaffGender LIKE 'Female') NOT NULL,
	StaffSalary INT NOT NULL
)

CREATE TABLE MsSupplier(
	SupplierId VARCHAR(5) PRIMARY KEY CHECK(SupplierId LIKE 'SU[0-9][0-9][0-9]') NOT NULL,
	SupplierName CHAR(50) CHECK(LEN (SupplierName) > 6) NOT NULL,
	SupplierPhoneNumber VARCHAR(15) NOT NULL,
	SupplierAddress VARCHAR(100) NOT NULL
)

CREATE TABLE MsPayment(
	PaymentTypeId VARCHAR(5) PRIMARY KEY CHECK(PaymentTypeId LIKE 'PA[0-9][0-9][0-9]') NOT NULL,
	PaymentType VARCHAR(15) NOT NULL
)

CREATE TABLE MsMaterial(
	MaterialId VARCHAR(5) PRIMARY KEY CHECK(MaterialId LIKE 'MA[0-9][0-9][0-9]') NOT NULL,
	MaterialName CHAR(100) NOT NULL,
	MaterialPrice INT CHECK(MaterialPrice > 0) NOT NULL
)

CREATE TABLE MsCloth(
	ClothId VARCHAR(5) PRIMARY KEY CHECK(ClothId LIKE'CL[0-9][0-9][0-9]') NOT NULL,
	ClothName VARCHAR(50) NOT NULL,
	ClothStock INT CHECK (ClothStock > 0 AND ClothStock < 250) NOT NULL,
	ClothPrice INT NOT NULL
)

CREATE TABLE purchaseTransactionHeader(
	PurchaseId VARCHAR(5) PRIMARY KEY CHECK(PurchaseId LIKE'PU[0-9][0-9][0-9]') NOT NULL,
	StaffId VARCHAR(5) FOREIGN KEY REFERENCES MsStaff(StaffId) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	SupplierId VARCHAR(5) FOREIGN KEY REFERENCES MsSupplier(SupplierId) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	TransactionDate DATE NOT NULL,
	PaymentTypeId VARCHAR(5) FOREIGN KEY REFERENCES MsPayment(PaymentTypeId) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
)

CREATE TABLE purchaseTransactionDetail(
	PurchaseId VARCHAR(5) PRIMARY KEY FOREIGN KEY REFERENCES purchaseTransactionHeader(PurchaseId) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	MaterialId VARCHAR(5) FOREIGN KEY REFERENCES MsMaterial(MaterialId) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	PurchaseQuantity INT NOT NULL
)

CREATE TABLE salesTransactionHeader(
	SalesId VARCHAR(5) PRIMARY KEY CHECK(SalesId LIKE 'SA[0-9][0-9][0-9]') NOT NULL,
	StaffId VARCHAR(5) FOREIGN KEY REFERENCES MsStaff(StaffId) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	CustomerId VARCHAR(5) FOREIGN KEY REFERENCES MsCustomer(CustomerId) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	TransactionDate DATE NOT NULL,
	PaymentTypeId VARCHAR(5) FOREIGN KEY REFERENCES MsPayment(PaymentTypeId) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
)

CREATE TABLE salesTransactionDetail(
	SalesId VARCHAR(5) PRIMARY KEY FOREIGN KEY REFERENCES salesTransactionHeader(SalesId) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	ClothId VARCHAR(5) FOREIGN KEY REFERENCES MsCloth(ClothId) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	SalesQuantity INT NOT NULL
)
